spring:
  application:
    name: eureka-server

server:
  port: 2001 #默认8761

eureka:
  server:
    enable-self-preservation: false
  instance:
    hostname: eureka1  # 主机名，eureka集群中使用hostname来区分多态服务器
  client:
    register-with-eureka: false
    fetch-registry: false

